### ISSUE TITLE
Put in the wrong account info. How do I change them?

### ISSUE THREAD

**Issue by Cumol** [wandersoncferreira/helm-spotify-plus#29]
When first running help-spotify-plus I was asked for my username and password. I did a mistake and now nothing seems to work. Any idea how to change them?

**Comment by wandersoncferreira** [comment]
Hello Cumol,

I think that something changed in the Spotify API web service because this package was not supposed to ask you for any user and password.

I just tried that today and I was aked for the same. I will try to investigate this better this weekend.

Thanks for the report!

**Comment by wandersoncferreira** [comment]
@Cumol the Spotify Web API removed all the unauthenticated methods from their API. That's why now we need to refactor the code and be compliant with the new methods.

more on this news: https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/

I am actually a lot busy, so I would appreciate if someone else could take care of that. Either way, I will try to work at it the next month.


Sorry for the problem!

**Comment by Githeo** [comment]
the error in process filter: wrong type argument: char-or-string-p, nil is for the new authentication model?

**Comment by wandersoncferreira** [comment]
I am sorry for taking too long to fix it. However, now the user **do not need to register its password neither username** for the package to work. You should have zero impact on your previous user experience.

I will close this issue, any points for discussion please open a new one. Thanks!
